- type: randomHumanoidSettings
  id: VisitorSeniorCooker
  parent: EventHumanoid
  speciesBlacklist:
    - Diona
    - Moth
    - Arachnid
    - Dwarf
    - Vox
    - Reptilian
    - Vulpkanin
  components:
    - type: GhostRole
      name: ghost-role-information-cooker-name
      description: ghost-role-information-cooker-description
      rules: ghost-role-information-freeagent-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes:
        - VisitorWalter
      roleLoadout: [ RoleSurvivalExtended ]
    - type: Skill
      WeaponLevel: 0
      MedicineLevel: 2
      EngineeringLevel: 2
      Research: false
      Piloting: true
      MusInstruments: true
      Botany: true
      Bureaucracy: true

- type: randomHumanoidSettings
  id: VisitorJuniorCooker
  parent: EventHumanoid
  speciesBlacklist:
    - Diona
    - Moth
    - Arachnid
    - Dwarf
    - Vox
    - Reptilian
    - Vulpkanin
  components:
    - type: GhostRole
      name: ghost-role-information-cooker-name
      description: ghost-role-information-cooker-description
      rules: ghost-role-information-freeagent-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes:
        - VisitorJessy
      roleLoadout: [ RoleSurvivalExtended ]
    - type: Skill
      WeaponLevel: 2
      MedicineLevel: 2
      EngineeringLevel: 0
      Research: false
      Piloting: true
      MusInstruments: true
      Botany: true
      Bureaucracy: true
